### ISSUE TITLE
ILL FIX IT WITH OUR PLUGIN DEVELOPMENT TEAM!

### ISSUE THREAD

**Issue by matthew4444** [DavidJBrockway/SkyWars-old-mg76-#1]
WANNNA JOIN IT,I SENT U AN INVTATION TO GITHUB.COM/NETHERMANIACSKINGDOM

**Comment by DavidJBrockway** [comment]
Hi it skywars old been doing some upgrades still won't work erro is in map slyblockgeerator

**Comment by DavidJBrockway** [comment]
Ok ivite me I update his spleef working on world edit next need wand fiz

**Comment by DavidJBrockway** [comment]
Code erro in https://github.com/DavidJBrockway/SkyWars-old-mg76-/blob/master/src/mcg76/skywars/map/SkyBlockGenerator.php It on line 284 to 294

**Comment by DavidJBrockway** [comment]
Me and my friend he a plugin Dev to are working on a fix right now but May not work

**Comment by matthew4444** [comment]
were r also

**Comment by matthew4444** [comment]
wanna be in our group also

**Comment by DavidJBrockway** [comment]
Invite plz

**Comment by matthew4444** [comment]
ok

**Comment by DavidJBrockway** [comment]
We have found a fix did not work we trying to re code the erro part

**Comment by DavidJBrockway** [comment]
I have his old world edit it has wand erro

**Comment by DavidJBrockway** [comment]
Updated his spleef

**Comment by matthew4444** [comment]
go here **https://github.com/NetherManiacsKingdom**

**Comment by DavidJBrockway** [comment]
K I see you have plugin code there

**Comment by matthew4444** [comment]
r u a owner thier yet

**Comment by matthew4444** [comment]
u get invation yet?

**Comment by DavidJBrockway** [comment]
What

**Comment by DavidJBrockway** [comment]
Mope

**Comment by matthew4444** [comment]
?

**Comment by DavidJBrockway** [comment]
Now I am

**Comment by matthew4444** [comment]
ok

**Comment by matthew4444** [comment]
now

**Comment by DavidJBrockway** [comment]
What do now

**Comment by matthew4444** [comment]
umm
@flaxues is on

**Comment by matthew4444** [comment]
ill give u a link

**Comment by matthew4444** [comment]
https://github.com/NetherManiacsKingdom/BlazingRodGun/pull/1#discussion_r53746248

**Comment by DavidJBrockway** [comment]
Here https://github.com/DavidJBrockway/SkyWars-old-mg76-/blob/master/src/mcg76/skywars/map/SkyBlockGenerator.php line erro It on line 284 to 294

**Comment by matthew4444** [comment]
k

**Comment by DavidJBrockway** [comment]
Did you fix it yet

**Comment by DavidJBrockway** [comment]
It fixed
